{
    'name': 'Smart button devis',
    'version': '1.0.0',
    'category': '',
    'sequence': 1,
    'author': '',
    'summary': 'smart button devis',
    'description': "",
    'depends': ['sale', 'office_sale_devis'],
    'data': ['mysbdelivery.xml'],
    'js': [],
    'qweb': [],
    'css': [],
    'installable': True,
    'application': False,
    'auto_install': False,
}